//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace @__InformationTechnology__Circle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutorizationStaff
    {
        public int ID { get; set; }
        public int Staff { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Staff Staff1 { get; set; }
    }
}
