//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace @__InformationTechnology__Circle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Administrator = new HashSet<Administrator>();
            this.AutorizationUser = new HashSet<AutorizationUser>();
            this.AutorizationUser1 = new HashSet<AutorizationUser>();
            this.AutorizationUser2 = new HashSet<AutorizationUser>();
            this.ExtracurricularActivities = new HashSet<ExtracurricularActivities>();
        }
    
        public int ID_U { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Fname { get; set; }
        public bool Sex { get; set; }
        public string Phone { get; set; }
        public string PasspNumber { get; set; }
        public string PasspOrg { get; set; }
        public System.DateTime PasspDate { get; set; }
        public string INN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Administrator> Administrator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorizationUser> AutorizationUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorizationUser> AutorizationUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorizationUser> AutorizationUser2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtracurricularActivities> ExtracurricularActivities { get; set; }
    }
}
